# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fKqGENiyDMLsavgH8U6c1zWF5CjjEz99
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab Notebooks/mini_project

#pip install flask-ngrok


#!curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok



#!ngrok authtoken 25aj4CGWAiSUzsQdyjBgVxW8bst_VMzp2GRWTKvzpSzZiaHS

from flask_ngrok import run_with_ngrok
from flask import Flask,request,render_template
import pickle
import numpy as np

#pip install surprise



from flask.templating import render_template_string
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 11 18:33:38 2021

@author: MY BOOK
"""

import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

app = Flask(__name__)
run_with_ngrok(app)
model = pickle.load(open('model.pkl', 'rb'))
temp= pickle.load(open('svd.pkl', 'rb'))
@app.route('/')
def home():
    return render_template('dress home.html')

@app.route('/predict',methods=['POST'])
def predict():
  weight=float(request.form["weight"])
  bust_size1=float(request.form["bust size1"])
  size=float(request.form["size"])
  height = float(request.form["height"])
  age = int(request.form["age"])
  bust_size = float(request.form["bust_size"])
  occasion = request.form["occasion"]
  #session['ans']=str(occasion)
  arr=np.array([weight,age,height,bust_size,bust_size1,size])
  answer=predict(arr)#predict body type
  arr1=np.array([answer,occasion])
  result=predict(arr1)
  #session['ansi']=str(answer)
  return render_template('recom.html',answer=result)
  
'''
@app.route('/predict_api',methods=['POST'])
def predict_api():
  ans=session.get('ans')
  ansi=session.get('ansi')
  result=np.array([ans,ansi])
  recomm=model.predict(result)
  return recomm
  '''
 
'''
app1=Flask(__name__)
run_with_ngrok(app1)
mod=pickle.load(open('model.pkl','rb'))
modd=pickle.load(open('svd.pkl','rb'))
@app1.route('/')
def home():
  return render_template('recom.html')
@app1.route('/prediction',methods=['POST'])
def prediction:
'''

if __name__ == "__main__":
    app.run(debug=True)

#app.run()